---
title: "`dplyr` Practice Homework"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../styles.css
  pdf_document: default
---


# Using the `dplyr` verbs

Use the `salaries.csv` dataset to answer the following questions:

1.	Use `select` to see the beginning salary variable and the current salary variable.
2.	Use `filter` to see the employees aged over 50, who have a salary over £20,000.
3.	Use `arrange` to order by the data so that the highest salaries are first.
4.	Use `mutate` to make a new variables beginning_salary_pence and current_salary_pence. These should have the corresponding salaries in pence instead of pounds.
5.	Use `summarise` to find the maximum age and the minimum age.
6.	Find the minimum salary and the maximum salary.
7.	Find all the employees aged under 30.
8.	Order the data in terms of increasing educational level where ties are broken using age.
9.	Drop all the non-numeric variables in the tibble.
10.	Find all employees with either less than 2 years work experience or an education level below 12.
11.	Transform the salary variables so they measure how many 1000s of pounds each salary is.
12.	Find all the females employees with an employment category of 'security officer'.

# Pipes

Again, answer these questions using the `salaries.csv` dataset:

1.	Find the average salary per educational level, for educational levels of 16 and below. Arrange the results from highest salary to lowest. Answer using pipes.
2.	Find the average salary for each gender in each employment category. Exclude any employees with less than 2 years of work experience. Answer using pipes.
3.	For each employment category find the difference between the mean salary and the median salary. Arrange so that the greatest difference comes first. Answer using pipes. (The difference between mean salary and median salary gives us a measure of how skewed salaries - we'll come on to this shortly!)

# Missing values exercise

In this exercise we will be looking at the beer calorie data (dataset `beer.txt`). To read this data, use the `read_delim()` function, specifying `;` as the delimiter.

1.	Find all the observations where the carbohydrates are missing.
2.	Find all the observations where the brand is missing.
3.	What is different about the observations missing carbohydrates and the observations missing brand? To clean the data should we drop the rows missing brand or the rows missing carbohydrates?

# Recoding excercise 

Use the dataset `inmates.tsv` for these questions. Investigate a function to read data in this format.

<details>
<summary>**Hint**</summary>
`read_tsv()`
</details>
<br>
